// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data.Configurations;
using VentasNet.Entity.Models;
#nullable disable

namespace VentasNet.Entity.Data
{
    public partial class VentasNetContext : DbContext
    {
        public VentasNetContext()
        {
        }

        public VentasNetContext(DbContextOptions<VentasNetContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VwUsuario> VwUsuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(VentasNetContext).Assembly);

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
